"""updated user with vpn devices mapping

Revision ID: 01746e536cd5
Revises: b8e4f1a92c0d
Create Date: 2026-05-29 13:56:39.743322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01746e536cd5'
down_revision: Union[str, Sequence[str], None] = 'b8e4f1a92c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vpn_device_uuid', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('vpn_device_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('vpn_device_type', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('vpn_provisioned_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_vpn_device_uuid'), 'users', ['vpn_device_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vpn_device_uuid'), table_name='users')
    op.drop_column('users', 'vpn_provisioned_at')
    op.drop_column('users', 'vpn_device_type')
    op.drop_column('users', 'vpn_device_name')
    op.drop_column('users', 'vpn_device_uuid')
    # ### end Alembic commands ###
