"""initial schema

Revision ID: 039d26aad928
Revises: 
Create Date: 2026-03-05 13:44:08.516107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '039d26aad928'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_categories_uuid'), 'product_categories', ['uuid'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('address', sa.String(length=128), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_warehouses_name'),
    sa.UniqueConstraint('warehouse_code', name='uq_warehouses_code')
    )
    op.create_index(op.f('ix_warehouses_uuid'), 'warehouses', ['uuid'], unique=True)
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_category_id', 'name', name='uq_checklists_category_name')
    )
    op.create_index('ix_checklists_category_active', 'checklists', ['product_category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_checklists_product_category_id'), 'checklists', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_checklists_uuid'), 'checklists', ['uuid'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=False),
    sa.Column('batch_number', sa.String(length=64), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', name='uq_products_serial_number')
    )
    op.create_index('ix_products_category_active', 'products', ['product_category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_product_category_id'), 'products', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('designation', sa.String(length=120), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('checklist_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('group_order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'group_order_idx', name='uq_checklist_groups_order_idx'),
    sa.UniqueConstraint('checklist_id', 'name', name='uq_checklist_groups_checklist_name')
    )
    op.create_index('ix_checklist_groups_checklist_active', 'checklist_groups', ['checklist_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_checklist_groups_checklist_id'), 'checklist_groups', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_checklist_groups_uuid'), 'checklist_groups', ['uuid'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=32), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('proxy_ip_address', postgresql.INET(), nullable=True),
    sa.Column('current_lat', sa.Double(), nullable=True),
    sa.Column('current_lng', sa.Double(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_fingerprint', name='uq_devices_device_fingerprint'),
    sa.UniqueConstraint('imei', name='uq_devices_imei')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index('ix_devices_user_id_active', 'devices', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.create_table('checklist_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('checklist_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('dropdown_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_order_idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_group_id'], ['checklist_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_group_id', 'field_order_idx', name='uq_checklist_fields_order_idx'),
    sa.UniqueConstraint('checklist_group_id', 'name', name='uq_checklist_fields_group_name')
    )
    op.create_index(op.f('ix_checklist_fields_checklist_group_id'), 'checklist_fields', ['checklist_group_id'], unique=False)
    op.create_index('ix_checklist_fields_checklist_id', 'checklist_fields', ['checklist_id'], unique=False)
    op.create_index('ix_checklist_fields_group_active', 'checklist_fields', ['checklist_group_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_checklist_fields_uuid'), 'checklist_fields', ['uuid'], unique=True)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=16), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_checklist_active', 'inspections', ['checklist_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspections_checklist_id'), 'inspections', ['checklist_id'], unique=False)
    op.create_index('ix_inspections_device_active', 'inspections', ['device_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspections_device_id'), 'inspections', ['device_id'], unique=False)
    op.create_index('ix_inspections_inspector_active', 'inspections', ['inspector_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspections_inspector_id'), 'inspections', ['inspector_id'], unique=False)
    op.create_index('ix_inspections_product_active', 'inspections', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspections_product_id'), 'inspections', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspections_uuid'), 'inspections', ['uuid'], unique=True)
    op.create_table('inspection_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('remarks', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_images_inspection_active', 'inspection_images', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_images_inspection_id'), 'inspection_images', ['inspection_id'], unique=False)
    op.create_index('ix_inspection_images_product_active', 'inspection_images', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_images_product_id'), 'inspection_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspection_images_uuid'), 'inspection_images', ['uuid'], unique=True)
    op.create_table('inspection_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_field_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=180), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('remarks', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_field_id'], ['checklist_fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'checklist_field_id', name='uq_inspection_inputs_one_per_field')
    )
    op.create_index(op.f('ix_inspection_inputs_checklist_field_id'), 'inspection_inputs', ['checklist_field_id'], unique=False)
    op.create_index('ix_inspection_inputs_inspection_active', 'inspection_inputs', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_inspection_id'), 'inspection_inputs', ['inspection_id'], unique=False)
    op.create_index('ix_inspection_inputs_product_active', 'inspection_inputs', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_product_id'), 'inspection_inputs', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_uuid'), 'inspection_inputs', ['uuid'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.String(length=16), server_default='info', nullable=False),
    sa.Column('log_value', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logs_device_active', 'logs', ['device_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_device_id'), 'logs', ['device_id'], unique=False)
    op.create_index('ix_logs_inspection_active', 'logs', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_inspection_id'), 'logs', ['inspection_id'], unique=False)
    op.create_index('ix_logs_product_active', 'logs', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_product_id'), 'logs', ['product_id'], unique=False)
    op.create_index('ix_logs_user_active', 'logs', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_uuid'), 'logs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_uuid'), table_name='logs')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index('ix_logs_user_active', table_name='logs')
    op.drop_index(op.f('ix_logs_product_id'), table_name='logs')
    op.drop_index('ix_logs_product_active', table_name='logs')
    op.drop_index(op.f('ix_logs_inspection_id'), table_name='logs')
    op.drop_index('ix_logs_inspection_active', table_name='logs')
    op.drop_index(op.f('ix_logs_device_id'), table_name='logs')
    op.drop_index('ix_logs_device_active', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_inspection_inputs_uuid'), table_name='inspection_inputs')
    op.drop_index(op.f('ix_inspection_inputs_product_id'), table_name='inspection_inputs')
    op.drop_index('ix_inspection_inputs_product_active', table_name='inspection_inputs')
    op.drop_index(op.f('ix_inspection_inputs_inspection_id'), table_name='inspection_inputs')
    op.drop_index('ix_inspection_inputs_inspection_active', table_name='inspection_inputs')
    op.drop_index(op.f('ix_inspection_inputs_checklist_field_id'), table_name='inspection_inputs')
    op.drop_table('inspection_inputs')
    op.drop_index(op.f('ix_inspection_images_uuid'), table_name='inspection_images')
    op.drop_index(op.f('ix_inspection_images_product_id'), table_name='inspection_images')
    op.drop_index('ix_inspection_images_product_active', table_name='inspection_images')
    op.drop_index(op.f('ix_inspection_images_inspection_id'), table_name='inspection_images')
    op.drop_index('ix_inspection_images_inspection_active', table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index(op.f('ix_inspections_uuid'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_product_id'), table_name='inspections')
    op.drop_index('ix_inspections_product_active', table_name='inspections')
    op.drop_index(op.f('ix_inspections_inspector_id'), table_name='inspections')
    op.drop_index('ix_inspections_inspector_active', table_name='inspections')
    op.drop_index(op.f('ix_inspections_device_id'), table_name='inspections')
    op.drop_index('ix_inspections_device_active', table_name='inspections')
    op.drop_index(op.f('ix_inspections_checklist_id'), table_name='inspections')
    op.drop_index('ix_inspections_checklist_active', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_checklist_fields_uuid'), table_name='checklist_fields')
    op.drop_index('ix_checklist_fields_group_active', table_name='checklist_fields')
    op.drop_index('ix_checklist_fields_checklist_id', table_name='checklist_fields')
    op.drop_index(op.f('ix_checklist_fields_checklist_group_id'), table_name='checklist_fields')
    op.drop_table('checklist_fields')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.drop_index('ix_devices_user_id_active', table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_checklist_groups_uuid'), table_name='checklist_groups')
    op.drop_index(op.f('ix_checklist_groups_checklist_id'), table_name='checklist_groups')
    op.drop_index('ix_checklist_groups_checklist_active', table_name='checklist_groups')
    op.drop_table('checklist_groups')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_product_category_id'), table_name='products')
    op.drop_index('ix_products_category_active', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_checklists_uuid'), table_name='checklists')
    op.drop_index(op.f('ix_checklists_product_category_id'), table_name='checklists')
    op.drop_index('ix_checklists_category_active', table_name='checklists')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_warehouses_uuid'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_uuid'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
