"""updated attribute to side images

Revision ID: 04899d035bcf
Revises: 4f12221eae80
Create Date: 2026-05-05 21:27:09.012266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04899d035bcf'
down_revision: Union[str, Sequence[str], None] = '4f12221eae80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('outer_packaging_side_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('inner_packaging_side_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('product_side_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('inspections', 'product_images')
    op.drop_column('inspections', 'outer_packaging_images')
    op.drop_column('inspections', 'inner_packaging_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('inner_packaging_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('inspections', sa.Column('outer_packaging_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('inspections', sa.Column('product_images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('inspections', 'product_side_images')
    op.drop_column('inspections', 'inner_packaging_side_images')
    op.drop_column('inspections', 'outer_packaging_side_images')
    # ### end Alembic commands ###
