"""add plants and warehouse location columns

Revision ID: 1423fee6d824
Revises: 039d26aad928
Create Date: 2026-04-24 19:04:03.737383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1423fee6d824'
down_revision: Union[str, Sequence[str], None] = '039d26aad928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('address', sa.String(length=128), server_default='', nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_plants_name'),
    sa.UniqueConstraint('plant_code', name='uq_plants_code')
    )
    op.create_index(op.f('ix_plants_uuid'), 'plants', ['uuid'], unique=True)
    op.add_column('warehouses', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('warehouses', sa.Column('postal_code', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'postal_code')
    op.drop_column('warehouses', 'city')
    op.drop_index(op.f('ix_plants_uuid'), table_name='plants')
    op.drop_table('plants')
    # ### end Alembic commands ###
