"""updated forgot password requests

Revision ID: 19a78f975b5c
Revises: 3c3d9b849c37
Create Date: 2026-06-14 00:30:39.409430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a78f975b5c'
down_revision: Union[str, Sequence[str], None] = '3c3d9b849c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_requests', sa.Column('is_disallowed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_reset_requests', 'is_disallowed')
    # ### end Alembic commands ###
