"""push notifications setup

Revision ID: 2f0d56523fea
Revises: 04899d035bcf
Create Date: 2026-05-13 21:51:27.990501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f0d56523fea'
down_revision: Union[str, Sequence[str], None] = '04899d035bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('expiration_time', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), server_default='', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_subscriptions_endpoint')
    )
    op.create_index('ix_push_subscriptions_device_active', 'push_subscriptions', ['device_id', 'is_active'], unique=False)
    op.create_index('ix_push_subscriptions_device_fingerprint_active', 'push_subscriptions', ['device_fingerprint', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_device_id'), 'push_subscriptions', ['device_id'], unique=False)
    op.create_index('ix_push_subscriptions_user_active', 'push_subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_uuid'), 'push_subscriptions', ['uuid'], unique=True)
    op.create_table('push_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('push_subscription_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), server_default='/', nullable=False),
    sa.Column('tag', sa.String(length=128), server_default='', nullable=False),
    sa.Column('icon', sa.String(length=1024), nullable=True),
    sa.Column('badge', sa.String(length=1024), nullable=True),
    sa.Column('payload_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='push_notification_status', native_enum=False, create_constraint=True, length=16), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_status_code', sa.Integer(), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['push_subscription_id'], ['push_subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_notifications_device_id'), 'push_notifications', ['device_id'], unique=False)
    op.create_index(op.f('ix_push_notifications_push_subscription_id'), 'push_notifications', ['push_subscription_id'], unique=False)
    op.create_index(op.f('ix_push_notifications_status'), 'push_notifications', ['status'], unique=False)
    op.create_index('ix_push_notifications_status_created', 'push_notifications', ['status', 'created_at'], unique=False)
    op.create_index('ix_push_notifications_subscription', 'push_notifications', ['push_subscription_id'], unique=False)
    op.create_index('ix_push_notifications_user_created', 'push_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_push_notifications_user_id'), 'push_notifications', ['user_id'], unique=False)
    op.create_index('ix_push_notifications_user_status', 'push_notifications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_push_notifications_uuid'), 'push_notifications', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_notifications_uuid'), table_name='push_notifications')
    op.drop_index('ix_push_notifications_user_status', table_name='push_notifications')
    op.drop_index(op.f('ix_push_notifications_user_id'), table_name='push_notifications')
    op.drop_index('ix_push_notifications_user_created', table_name='push_notifications')
    op.drop_index('ix_push_notifications_subscription', table_name='push_notifications')
    op.drop_index('ix_push_notifications_status_created', table_name='push_notifications')
    op.drop_index(op.f('ix_push_notifications_status'), table_name='push_notifications')
    op.drop_index(op.f('ix_push_notifications_push_subscription_id'), table_name='push_notifications')
    op.drop_index(op.f('ix_push_notifications_device_id'), table_name='push_notifications')
    op.drop_table('push_notifications')
    op.drop_index(op.f('ix_push_subscriptions_uuid'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_user_active', table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_device_id'), table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_device_fingerprint_active', table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_device_active', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    # ### end Alembic commands ###
