"""added inspection status

Revision ID: 351589d6f873
Revises: 75a05c1d5bc5
Create Date: 2026-05-01 14:25:38.362597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351589d6f873'
down_revision: Union[str, Sequence[str], None] = '75a05c1d5bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('is_under_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('inspections', sa.Column('review_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='inspection_review_status', native_enum=False, create_constraint=True, length=20), server_default='PENDING', nullable=False))
    op.add_column('inspections', sa.Column('reviewer_id', sa.Integer(), nullable=True))
    op.add_column('inspections', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('inspections', sa.Column('reviewed_comment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_inspections_reviewer_id'), 'inspections', ['reviewer_id'], unique=False)
    op.create_foreign_key(None, 'inspections', 'users', ['reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_index(op.f('ix_inspections_reviewer_id'), table_name='inspections')
    op.drop_column('inspections', 'reviewed_comment')
    op.drop_column('inspections', 'reviewed_at')
    op.drop_column('inspections', 'reviewer_id')
    op.drop_column('inspections', 'review_status')
    op.drop_column('inspections', 'is_under_review')
    # ### end Alembic commands ###
