"""added ip metadata for login audit

Revision ID: 37c06d7f8a88
Revises: 2186fd42b9ca
Create Date: 2026-06-10 20:21:22.956179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c06d7f8a88'
down_revision: Union[str, Sequence[str], None] = '2186fd42b9ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_address_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('country_name', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('lookup_status', sa.Enum('pending', 'completed', 'failed', 'skipped', name='ip_lookup_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('lookup_source', sa.String(length=64), nullable=True),
    sa.Column('lookup_error', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('looked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', name='uq_ip_address_metadata_ip')
    )
    op.create_index(op.f('ix_ip_address_metadata_ip_address'), 'ip_address_metadata', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_address_metadata_ip_address'), table_name='ip_address_metadata')
    op.drop_table('ip_address_metadata')
    # ### end Alembic commands ###
