"""added forgot password requests

Revision ID: 3c3d9b849c37
Revises: f99dd1d8ed01
Create Date: 2026-06-14 00:19:25.028715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3d9b849c37'
down_revision: Union[str, Sequence[str], None] = 'f99dd1d8ed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_ip_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', name='uq_password_reset_ip_blocks_ip')
    )
    op.create_index('ix_password_reset_ip_blocks_blocked_until', 'password_reset_ip_blocks', ['blocked_until'], unique=False)
    op.create_table('password_reset_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attempted_email', sa.String(length=180), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('proxy_ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_requests_attempted_email'), 'password_reset_requests', ['attempted_email'], unique=False)
    op.create_index('ix_password_reset_requests_ip_address', 'password_reset_requests', ['ip_address'], unique=False)
    op.create_index('ix_password_reset_requests_ip_created_at', 'password_reset_requests', ['ip_address', 'created_at'], unique=False)
    op.create_index('ix_password_reset_requests_token_hash', 'password_reset_requests', ['token_hash'], unique=False)
    op.create_index('ix_password_reset_requests_user_completed', 'password_reset_requests', ['user_id', 'is_completed'], unique=False)
    op.create_index('ix_password_reset_requests_user_id', 'password_reset_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_requests_uuid'), 'password_reset_requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_requests_uuid'), table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_user_id', table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_user_completed', table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_token_hash', table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_ip_created_at', table_name='password_reset_requests')
    op.drop_index('ix_password_reset_requests_ip_address', table_name='password_reset_requests')
    op.drop_index(op.f('ix_password_reset_requests_attempted_email'), table_name='password_reset_requests')
    op.drop_table('password_reset_requests')
    op.drop_index('ix_password_reset_ip_blocks_blocked_until', table_name='password_reset_ip_blocks')
    op.drop_table('password_reset_ip_blocks')
    # ### end Alembic commands ###
