"""added job logs

Revision ID: 4496bcaea0f4
Revises: 01746e536cd5
Create Date: 2026-05-29 18:22:48.488469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4496bcaea0f4'
down_revision: Union[str, Sequence[str], None] = '01746e536cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='job_log_status', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('rows_updated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_logs_created_at', 'job_logs', ['created_at'], unique=False)
    op.create_index('ix_job_logs_job_name', 'job_logs', ['job_name'], unique=False)
    op.create_index('ix_job_logs_status', 'job_logs', ['status'], unique=False)
    op.create_index(op.f('ix_job_logs_uuid'), 'job_logs', ['uuid'], unique=True)
    op.add_column('inspections', sa.Column('is_auto_approved', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'is_auto_approved')
    op.drop_index(op.f('ix_job_logs_uuid'), table_name='job_logs')
    op.drop_index('ix_job_logs_status', table_name='job_logs')
    op.drop_index('ix_job_logs_job_name', table_name='job_logs')
    op.drop_index('ix_job_logs_created_at', table_name='job_logs')
    op.drop_table('job_logs')
    # ### end Alembic commands ###
