"""added package images and time taken

Revision ID: 4f12221eae80
Revises: 7453d710d8bb
Create Date: 2026-05-05 21:19:00.001486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f12221eae80'
down_revision: Union[str, Sequence[str], None] = '7453d710d8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('outer_packaging_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('inner_packaging_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('product_images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('inspections', sa.Column('device_time_taken', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspections', 'device_time_taken')
    op.drop_column('inspections', 'product_images')
    op.drop_column('inspections', 'inner_packaging_images')
    op.drop_column('inspections', 'outer_packaging_images')
    # ### end Alembic commands ###
