"""update composite key in product category

Revision ID: 60fd67886e56
Revises: b1b7169ccfd7
Create Date: 2026-04-24 23:37:32.235956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fd67886e56'
down_revision: Union[str, Sequence[str], None] = 'b1b7169ccfd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_categories', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=2048),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_product_categories_category_code'), 'product_categories', type_='unique')
    op.drop_constraint(op.f('uq_product_categories_name'), 'product_categories', type_='unique')
    op.create_unique_constraint('uq_product_categories_composite', 'product_categories', ['category_type', 'sub_category_type', 'category_code', 'category_description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_categories_composite', 'product_categories', type_='unique')
    op.create_unique_constraint(op.f('uq_product_categories_name'), 'product_categories', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_product_categories_category_code'), 'product_categories', ['category_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_categories', 'name',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
