"""added totp 2fa codes

Revision ID: 62d48e08d679
Revises: c4e8b1d92f70
Create Date: 2026-06-23 09:39:36.187591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d48e08d679'
down_revision: Union[str, Sequence[str], None] = 'c4e8b1d92f70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('two_factor_enforced', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('two_factor_enabled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled_at')
    op.drop_column('users', 'two_factor_enforced')
    op.drop_column('users', 'two_factor_secret')
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
