"""added barcode locks

Revision ID: 7453d710d8bb
Revises: facc573b99be
Create Date: 2026-05-03 18:58:30.908671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7453d710d8bb'
down_revision: Union[str, Sequence[str], None] = 'facc573b99be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('inspection_type', sa.Enum('inbound', 'outbound', name='inspection_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', 'inspection_type', name='uq_barcode_locks_barcode_inspection_type')
    )
    op.create_index('ix_barcode_locks_user_id', 'barcode_locks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_barcode_locks_user_id', table_name='barcode_locks')
    op.drop_table('barcode_locks')
    # ### end Alembic commands ###
