"""initial schema

Revision ID: 75a05c1d5bc5
Revises: 
Create Date: 2026-04-25 01:34:57.343561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75a05c1d5bc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.Enum('Outer Packaging', 'Inner Packaging', 'Product', name='checklist_group', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=False),
    sa.Column('item_text', sa.String(length=512), nullable=False),
    sa.Column('field_type', sa.Enum('dropdown', 'yes_no', 'date', 'free_text', name='checklist_field_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('dropdown_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('allows_remarks', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('photo_upload_rule', sa.Enum('none', 'when_no', 'optional', 'always', name='checklist_photo_upload_rule', native_enum=False, create_constraint=True, length=16), server_default='none', nullable=False),
    sa.Column('min_upload_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'item_text', name='uq_checklists_group_name_item_text')
    )
    op.create_index('ix_checklists_active', 'checklists', ['is_active'], unique=False)
    op.create_index(op.f('ix_checklists_uuid'), 'checklists', ['uuid'], unique=True)
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('address', sa.String(length=512), server_default='', nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_plants_name'),
    sa.UniqueConstraint('plant_code', name='uq_plants_code')
    )
    op.create_index(op.f('ix_plants_uuid'), 'plants', ['uuid'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category_type', sa.String(length=32), nullable=False),
    sa.Column('sub_category_type', sa.String(length=32), nullable=False),
    sa.Column('category_code', sa.String(length=128), nullable=False),
    sa.Column('category_description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_type', 'sub_category_type', 'category_code', 'category_description', name='uq_product_categories_composite')
    )
    op.create_index(op.f('ix_product_categories_uuid'), 'product_categories', ['uuid'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('sub_category', sa.String(length=120), nullable=False),
    sa.Column('category_code', sa.String(length=120), nullable=False),
    sa.Column('category_description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('material_code', sa.String(length=120), nullable=False),
    sa.Column('material_description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code', name='uq_skus_material_code')
    )
    op.create_index('ix_skus_category_active', 'skus', ['category', 'is_active'], unique=False)
    op.create_index(op.f('ix_skus_uuid'), 'skus', ['uuid'], unique=True)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('address', sa.String(length=512), server_default='', nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_warehouses_name'),
    sa.UniqueConstraint('warehouse_code', name='uq_warehouses_code')
    )
    op.create_index(op.f('ix_warehouses_uuid'), 'warehouses', ['uuid'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=120), nullable=False),
    sa.Column('material_description', sa.String(length=512), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code', name='uq_products_material_code')
    )
    op.create_index('ix_products_category_active', 'products', ['product_category_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_products_product_category_id'), 'products', ['product_category_id'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('designation', sa.String(length=120), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_mobile_number'), 'users', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('imei', sa.String(length=48), nullable=False),
    sa.Column('device_type', sa.Enum('desktop', 'mobile', name='device_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), server_default='', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('proxy_ip_address', postgresql.INET(), nullable=True),
    sa.Column('current_lat', sa.Double(), nullable=True),
    sa.Column('current_lng', sa.Double(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_fingerprint', name='uq_devices_device_fingerprint'),
    sa.UniqueConstraint('imei', name='uq_devices_imei')
    )
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index('ix_devices_user_id_active', 'devices', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.create_table('product_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barcode', name='uq_product_units_barcode')
    )
    op.create_index('ix_product_units_product_active', 'product_units', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_product_units_product_id'), 'product_units', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_units_uuid'), 'product_units', ['uuid'], unique=True)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.Enum('inbound', 'outbound', name='inspection_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('product_unit_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_category_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.Column('plant_code', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('serial_number', sa.String(length=64), nullable=True),
    sa.Column('manufactured_year', sa.Integer(), nullable=True),
    sa.Column('truck_number', sa.String(length=64), nullable=True),
    sa.Column('truck_docking_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dock_number', sa.String(length=64), nullable=True),
    sa.Column('damage_type', sa.Enum('packaging', 'cosmetic', 'accessories', name='damage_type', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('damage_severity', sa.Enum('minor', 'major', name='damage_severity', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('damage_likely_cause', sa.Enum('transit', 'handling', 'packaging', 'manufacturing', name='damage_likely_cause', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('damage_grading', sa.Enum('DGR', 'LDGR', 'SCRAP', name='damage_grading', native_enum=False, create_constraint=True, length=16), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plant_code'], ['plants.plant_code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_unit_id'], ['product_units.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_code'], ['warehouses.warehouse_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_active_created_at', 'inspections', ['is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_damage_grading_active', 'inspections', ['damage_grading', 'is_active'], unique=False)
    op.create_index('ix_inspections_damage_likely_cause_active', 'inspections', ['damage_likely_cause', 'is_active'], unique=False)
    op.create_index('ix_inspections_damage_severity_active', 'inspections', ['damage_severity', 'is_active'], unique=False)
    op.create_index('ix_inspections_damage_type_active', 'inspections', ['damage_type', 'is_active'], unique=False)
    op.create_index('ix_inspections_device_active_created', 'inspections', ['device_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_inspector_active_created', 'inspections', ['inspector_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_plant_code_active_created', 'inspections', ['plant_code', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_product_active_created', 'inspections', ['product_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_product_category_active_created', 'inspections', ['product_category_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_product_unit_active_created', 'inspections', ['product_unit_id', 'is_active', 'created_at'], unique=False)
    op.create_index('ix_inspections_type_active_created', 'inspections', ['inspection_type', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_inspections_uuid'), 'inspections', ['uuid'], unique=True)
    op.create_index('ix_inspections_warehouse_code_active_created', 'inspections', ['warehouse_code', 'is_active', 'created_at'], unique=False)
    op.create_table('inspection_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('remarks', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_images_checklist_active', 'inspection_images', ['checklist_id', 'is_active'], unique=False)
    op.create_index('ix_inspection_images_inspection_active', 'inspection_images', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_images_inspection_id'), 'inspection_images', ['inspection_id'], unique=False)
    op.create_index('ix_inspection_images_product_active', 'inspection_images', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_images_product_id'), 'inspection_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspection_images_uuid'), 'inspection_images', ['uuid'], unique=True)
    op.create_table('inspection_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('remarks', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id', 'checklist_id', name='uq_inspection_inputs_one_per_item')
    )
    op.create_index('ix_inspection_inputs_checklist_id', 'inspection_inputs', ['checklist_id'], unique=False)
    op.create_index('ix_inspection_inputs_inspection_active', 'inspection_inputs', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_inspection_id'), 'inspection_inputs', ['inspection_id'], unique=False)
    op.create_index('ix_inspection_inputs_product_active', 'inspection_inputs', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_product_id'), 'inspection_inputs', ['product_id'], unique=False)
    op.create_index(op.f('ix_inspection_inputs_uuid'), 'inspection_inputs', ['uuid'], unique=True)
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('inspection_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.Enum('debug', 'info', 'warning', 'error', name='log_level', native_enum=False, create_constraint=True, length=16), server_default='info', nullable=False),
    sa.Column('log_value', sa.Text(), server_default='', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logs_device_active', 'logs', ['device_id', 'is_active'], unique=False)
    op.create_index('ix_logs_device_active_created_at', 'logs', ['device_id', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_logs_device_id'), 'logs', ['device_id'], unique=False)
    op.create_index('ix_logs_inspection_active', 'logs', ['inspection_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_inspection_id'), 'logs', ['inspection_id'], unique=False)
    op.create_index('ix_logs_product_active', 'logs', ['product_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_logs_product_id'), 'logs', ['product_id'], unique=False)
    op.create_index('ix_logs_user_active', 'logs', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_logs_user_active_created_at', 'logs', ['user_id', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_uuid'), 'logs', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_uuid'), table_name='logs')
    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')
    op.drop_index('ix_logs_user_active_created_at', table_name='logs')
    op.drop_index('ix_logs_user_active', table_name='logs')
    op.drop_index(op.f('ix_logs_product_id'), table_name='logs')
    op.drop_index('ix_logs_product_active', table_name='logs')
    op.drop_index(op.f('ix_logs_inspection_id'), table_name='logs')
    op.drop_index('ix_logs_inspection_active', table_name='logs')
    op.drop_index(op.f('ix_logs_device_id'), table_name='logs')
    op.drop_index('ix_logs_device_active_created_at', table_name='logs')
    op.drop_index('ix_logs_device_active', table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_inspection_inputs_uuid'), table_name='inspection_inputs')
    op.drop_index(op.f('ix_inspection_inputs_product_id'), table_name='inspection_inputs')
    op.drop_index('ix_inspection_inputs_product_active', table_name='inspection_inputs')
    op.drop_index(op.f('ix_inspection_inputs_inspection_id'), table_name='inspection_inputs')
    op.drop_index('ix_inspection_inputs_inspection_active', table_name='inspection_inputs')
    op.drop_index('ix_inspection_inputs_checklist_id', table_name='inspection_inputs')
    op.drop_table('inspection_inputs')
    op.drop_index(op.f('ix_inspection_images_uuid'), table_name='inspection_images')
    op.drop_index(op.f('ix_inspection_images_product_id'), table_name='inspection_images')
    op.drop_index('ix_inspection_images_product_active', table_name='inspection_images')
    op.drop_index(op.f('ix_inspection_images_inspection_id'), table_name='inspection_images')
    op.drop_index('ix_inspection_images_inspection_active', table_name='inspection_images')
    op.drop_index('ix_inspection_images_checklist_active', table_name='inspection_images')
    op.drop_table('inspection_images')
    op.drop_index('ix_inspections_warehouse_code_active_created', table_name='inspections')
    op.drop_index(op.f('ix_inspections_uuid'), table_name='inspections')
    op.drop_index('ix_inspections_type_active_created', table_name='inspections')
    op.drop_index('ix_inspections_product_unit_active_created', table_name='inspections')
    op.drop_index('ix_inspections_product_category_active_created', table_name='inspections')
    op.drop_index('ix_inspections_product_active_created', table_name='inspections')
    op.drop_index('ix_inspections_plant_code_active_created', table_name='inspections')
    op.drop_index('ix_inspections_inspector_active_created', table_name='inspections')
    op.drop_index('ix_inspections_device_active_created', table_name='inspections')
    op.drop_index('ix_inspections_damage_type_active', table_name='inspections')
    op.drop_index('ix_inspections_damage_severity_active', table_name='inspections')
    op.drop_index('ix_inspections_damage_likely_cause_active', table_name='inspections')
    op.drop_index('ix_inspections_damage_grading_active', table_name='inspections')
    op.drop_index('ix_inspections_active_created_at', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_product_units_uuid'), table_name='product_units')
    op.drop_index(op.f('ix_product_units_product_id'), table_name='product_units')
    op.drop_index('ix_product_units_product_active', table_name='product_units')
    op.drop_table('product_units')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.drop_index('ix_devices_user_id_active', table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_mobile_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_product_category_id'), table_name='products')
    op.drop_index('ix_products_category_active', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_warehouses_uuid'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_skus_uuid'), table_name='skus')
    op.drop_index('ix_skus_category_active', table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_categories_uuid'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_plants_uuid'), table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_checklists_uuid'), table_name='checklists')
    op.drop_index('ix_checklists_active', table_name='checklists')
    op.drop_table('checklists')
    # ### end Alembic commands ###
