"""updated inspection status by remove of pending status

Revision ID: 8610f8d6eb64
Revises: 351589d6f873
Create Date: 2026-05-01 14:38:25.722116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8610f8d6eb64'
down_revision: Union[str, Sequence[str], None] = '351589d6f873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
