"""update keysize in product category

Revision ID: 8e694a95eeab
Revises: 60fd67886e56
Create Date: 2026-04-24 23:56:09.129878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e694a95eeab'
down_revision: Union[str, Sequence[str], None] = '60fd67886e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_categories', 'name',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_categories', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)
    # ### end Alembic commands ###
