"""added user onboard password policy

Revision ID: a1f8168526c8
Revises: 19a78f975b5c
Create Date: 2026-06-14 00:50:39.123234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1f8168526c8'
down_revision: Union[str, Sequence[str], None] = '19a78f975b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_password_history_user_created_at', 'user_password_history', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_user_password_history_user_id', 'user_password_history', ['user_id'], unique=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'must_change_password')
    op.drop_index('ix_user_password_history_user_id', table_name='user_password_history')
    op.drop_index('ix_user_password_history_user_created_at', table_name='user_password_history')
    op.drop_table('user_password_history')
    # ### end Alembic commands ###
