"""added inspection review events

Revision ID: c3676aaec2dd
Revises: 8610f8d6eb64
Create Date: 2026-05-01 14:51:33.099967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3676aaec2dd'
down_revision: Union[str, Sequence[str], None] = '8610f8d6eb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='inspection_review_evt_from', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='inspection_review_evt_to', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspection_review_events_actor_user_id', 'inspection_review_events', ['actor_user_id'], unique=False)
    op.create_index('ix_inspection_review_events_inspection_created', 'inspection_review_events', ['inspection_id', 'created_at'], unique=False)
    op.create_index('ix_inspection_review_events_inspection_id', 'inspection_review_events', ['inspection_id'], unique=False)
    op.create_table('inspection_input_review_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_input_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('OK', 'FLAGGED', 'APPROVED', 'REJECTED', name='inspection_input_review_evt_from', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('OK', 'FLAGGED', 'APPROVED', 'REJECTED', name='inspection_input_review_evt_to', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspection_input_id'], ['inspection_inputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insp_input_review_events_actor_user_id', 'inspection_input_review_events', ['actor_user_id'], unique=False)
    op.create_index('ix_insp_input_review_events_input_created', 'inspection_input_review_events', ['inspection_input_id', 'created_at'], unique=False)
    op.create_index('ix_insp_input_review_events_input_id', 'inspection_input_review_events', ['inspection_input_id'], unique=False)
    op.add_column('inspection_inputs', sa.Column('input_review_status', sa.Enum('OK', 'FLAGGED', 'APPROVED', 'REJECTED', name='inspection_input_review_status', native_enum=False, create_constraint=True, length=20), server_default='OK', nullable=False))
    op.create_index('ix_inspection_inputs_input_review_status_active', 'inspection_inputs', ['input_review_status', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspection_inputs_input_review_status_active', table_name='inspection_inputs')
    op.drop_column('inspection_inputs', 'input_review_status')
    op.drop_index('ix_insp_input_review_events_input_id', table_name='inspection_input_review_events')
    op.drop_index('ix_insp_input_review_events_input_created', table_name='inspection_input_review_events')
    op.drop_index('ix_insp_input_review_events_actor_user_id', table_name='inspection_input_review_events')
    op.drop_table('inspection_input_review_events')
    op.drop_index('ix_inspection_review_events_inspection_id', table_name='inspection_review_events')
    op.drop_index('ix_inspection_review_events_inspection_created', table_name='inspection_review_events')
    op.drop_index('ix_inspection_review_events_actor_user_id', table_name='inspection_review_events')
    op.drop_table('inspection_review_events')
    # ### end Alembic commands ###
