"""add plant fk in inspection

Revision ID: d262d4985852
Revises: 5f3c1d9e8a11
Create Date: 2026-04-24 19:25:23.214636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd262d4985852'
down_revision: Union[str, Sequence[str], None] = '5f3c1d9e8a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspections', sa.Column('plant_code', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_inspections_plant_code'), 'inspections', ['plant_code'], unique=False)
    op.create_index('ix_inspections_plant_code_active', 'inspections', ['plant_code', 'is_active'], unique=False)
    op.create_foreign_key(None, 'inspections', 'plants', ['plant_code'], ['plant_code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inspections', type_='foreignkey')
    op.drop_index('ix_inspections_plant_code_active', table_name='inspections')
    op.drop_index(op.f('ix_inspections_plant_code'), table_name='inspections')
    op.drop_column('inspections', 'plant_code')
    # ### end Alembic commands ###
