"""added password change otp feature

Revision ID: d840a41095d5
Revises: a1f8168526c8
Create Date: 2026-06-14 01:47:03.006175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd840a41095d5'
down_revision: Union[str, Sequence[str], None] = 'a1f8168526c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_change_otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('proxy_ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_consumed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_change_otps_expires_at', 'password_change_otps', ['expires_at'], unique=False)
    op.create_index('ix_password_change_otps_user_id', 'password_change_otps', ['user_id'], unique=False)
    op.create_index('ix_password_change_otps_user_purpose_consumed', 'password_change_otps', ['user_id', 'purpose', 'is_consumed'], unique=False)
    op.create_index(op.f('ix_password_change_otps_uuid'), 'password_change_otps', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_change_otps_uuid'), table_name='password_change_otps')
    op.drop_index('ix_password_change_otps_user_purpose_consumed', table_name='password_change_otps')
    op.drop_index('ix_password_change_otps_user_id', table_name='password_change_otps')
    op.drop_index('ix_password_change_otps_expires_at', table_name='password_change_otps')
    op.drop_table('password_change_otps')
    # ### end Alembic commands ###
