"""remove columns from product

Revision ID: e736aa2fada2
Revises: d262d4985852
Create Date: 2026-04-24 20:21:37.059169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e736aa2fada2'
down_revision: Union[str, Sequence[str], None] = 'd262d4985852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('material_code', sa.String(length=120), nullable=False))
    op.add_column('products', sa.Column('material_description', sa.String(length=512), server_default='', nullable=False))
    op.drop_constraint(op.f('uq_products_serial_number'), 'products', type_='unique')
    op.create_unique_constraint('uq_products_material_code', 'products', ['material_code'])
    op.drop_column('products', 'manufacturing_date')
    op.drop_column('products', 'batch_number')
    op.drop_column('products', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('serial_number', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('batch_number', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('manufacturing_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_products_material_code', 'products', type_='unique')
    op.create_unique_constraint(op.f('uq_products_serial_number'), 'products', ['serial_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'material_description')
    op.drop_column('products', 'material_code')
    # ### end Alembic commands ###
